
#애플리케이션 포트 설정
server:
   port: 9090

#MySQL ?? ??
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/shop?serverTimezone=UTC
#    username: root
#    password: 1234
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    url: jdbc:log4jdbc:mysql://tivan-muscatdb.czwt78mf7f1j.ap-northeast-2.rds.amazonaws.com:3306/tivan-muscatdb?useSSL=false&autoReconnect=true
    url: jdbc:mysql://tivan-muscatdb.czwt78mf7f1j.ap-northeast-2.rds.amazonaws.com:3306/tivan-muscatdb?useSSL=false&autoReconnect=true
    username: admin
    password: qlqjs0spro
  jpa:
    properties:
      hibernate:
        show_sql: true #실행되는 쿼리 콘솔 출력
        format_sql: true #콘솔창에 출력되는 쿼리를 가독성이 좋게 포맷팅
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL8Dialect

#쿼리에 물음표로 출력되는 바인드 파라미터 출력
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace




